[General]
passwordCharacter=
passwordMask=true

passwordInputBackground={{colors.surface_container.default.hex}}80

passwordInputRadius=4

bar_width=0.2

passwordInputCursorVisible=false

font="JetBrainsMono Nerd Font Mono"
passwordFontSize=32
passwordTextColor=

showSessionsByDefault=false

sessionsFontSize=20

showUsersByDefault=false

usersFontSize=28

background=painting.jpg

backgroundFill=
backgroundFillMode=aspect

basicTextColor={{colors.on_surface.default.hex}}

blurRadius=20

passwordCursorColor={{colors.primary.default.hex}}