[General]
passwordCharacter=
passwordMask=true

passwordInputBackground=#1e1e1e80

passwordInputRadius=4

bar_width=0.2

passwordInputCursorVisible=false

font="JetBrainsMono Nerd Font Mono"
passwordFontSize=32
passwordTextColor=

showSessionsByDefault=false

sessionsFontSize=20

showUsersByDefault=false

usersFontSize=28

background=painting.jpg

backgroundFill=
backgroundFillMode=aspect

basicTextColor=#f0f0f0

blurRadius=20

passwordCursorColor=#ffffff