[General]
passwordCharacter=
passwordMask=true

passwordInputBackground=#32302f80

passwordInputRadius=4

bar_width=0.2

passwordInputCursorVisible=false

font="JetBrainsMono Nerd Font Mono"
passwordFontSize=32
passwordTextColor=

showSessionsByDefault=false

sessionsFontSize=20

showUsersByDefault=false

usersFontSize=28

background=painting.jpg

backgroundFill=
backgroundFillMode=aspect

basicTextColor=#ebdbb2

blurRadius=20

passwordCursorColor=#fe8019