# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282828"

# Main text color
theme[main_fg]="#ebdbb2"

# Title color for boxes
theme[title]="#ebdbb2"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#fe8019"

# Background color of selected item in processes box
theme[selected_bg]="#3c3836"

# Foreground color of selected item in processes box
theme[selected_fg]="#fe8019"

# Color of inactive/disabled text
theme[inactive_fg]="#928374"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#d5c4a1"

# Background color of the percentage meters
theme[meter_bg]="#3c3836"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d5c4a1"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#d3869b" #Mauve
theme[mem_box]="#b8bb26" #Green
theme[net_box]="#fb4934" #Maroon
theme[proc_box]="#fe8019" #Blue

# Box divider line and small boxes line color
theme[div_line]="#665c54"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#b8bb26"
theme[temp_mid]="#fabd2f"
theme[temp_end]="#fb4934"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#8ec07c"
theme[cpu_mid]="#458588"
theme[cpu_end]="#b16286"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#d3869b"
theme[free_mid]="#b16286"
theme[free_end]="#fe8019"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#458588"
theme[cached_mid]="#fe8019"
theme[cached_end]="#b16286"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#fe8019"
theme[available_mid]="#fb4934"
theme[available_end]="#fb4934"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#b8bb26"
theme[used_mid]="#8ec07c"
theme[used_end]="#83a598"

# Download graph colors (Peach -> Red)
theme[download_start]="#fe8019"
theme[download_mid]="#fb4934"
theme[download_end]="#fb4934"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#b8bb26"
theme[upload_mid]="#8ec07c"
theme[upload_end]="#83a598"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#458588"
theme[process_mid]="#83a598"
theme[process_end]="#d3869b"
