# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#161616"

# Main text color
theme[main_fg]="#f0f0f0"

# Title color for boxes
theme[title]="#f0f0f0"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ffffff"

# Background color of selected item in processes box
theme[selected_bg]="#2a2a2a"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#888888"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#d8d8d8"

# Background color of the percentage meters
theme[meter_bg]="#2a2a2a"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d8d8d8"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#9f9f9f" #Mauve
theme[mem_box]="#a9a9a9" #Green
theme[net_box]="#d0d0d0" #Maroon
theme[proc_box]="#ffffff" #Blue

# Box divider line and small boxes line color
theme[div_line]="#606060"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#a9a9a9"
theme[temp_mid]="#e0e0e0"
theme[temp_end]="#d0d0d0"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#a9a9a9"
theme[cpu_mid]="#707070"
theme[cpu_end]="#888888"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#9f9f9f"
theme[free_mid]="#888888"
theme[free_end]="#ffffff"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#707070"
theme[cached_mid]="#ffffff"
theme[cached_end]="#888888"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#ffffff"
theme[available_mid]="#d0d0d0"
theme[available_end]="#d0d0d0"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#a9a9a9"
theme[used_mid]="#a9a9a9"
theme[used_end]="#999999"

# Download graph colors (Peach -> Red)
theme[download_start]="#ffffff"
theme[download_mid]="#d0d0d0"
theme[download_end]="#d0d0d0"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#a9a9a9"
theme[upload_mid]="#a9a9a9"
theme[upload_end]="#999999"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#707070"
theme[process_mid]="#999999"
theme[process_end]="#9f9f9f"
