[frappe]
# Spicetify
text               = c6d0f5
subtext            = c6d0f5
main               = 303446
main-elevated      = 414559
highlight          = 404559
highlight-elevated = 51576d
sidebar            = 292C3C
player             = 232634
card               = 414559
shadow             = 292C3C
selected-row       = 949cbb
button             = 838BA7
button-active      = 949CBB
button-disabled    = 737994
tab-active         = 414559
notification       = 414559
notification-error = E78284
equalizer          = 000000
misc               = 51576d

# Catppuccin
crust              = 232634
mantle             = 292c3c
base               = 303446
surface0           = 414559
surface1           = 51576d
surface2	       = acb0be
overlay0           = 737994
overlay1           = 838ba7
overlay2           = 949cbb
rosewater          = f2d5cf
flamingo           = eebebe
pink               = f4b8e4
maroon             = ea999c
red                = e78284
peach              = ef9f76
yellow             = e5c890
green              = a6d189
teal               = 81c8be
sapphire           = 85c1dc
blue               = 8caaee
sky                = 99dadb
mauve              = ca9ee6
lavender           = babbf1


[latte]
# Spicetify
text               = 4c4f69
subtext            = 4c4f69
main               = EFF1F5
main-elevated      = ccd0da
highlight          = dddee5
highlight-elevated = bcc0cc
sidebar            = E6E9EF
player             = DCE0E8
card               = ccd0da
shadow             = E6E9EF
selected-row       = 7c7f93
button             = 8C8FA1
button-active      = 7C7F93
button-disabled    = 9CA0B0
tab-active         = ccd0da
notification       = ccd0da
notification-error = D20F39
equalizer          = 000000
misc               = bcc0cc

# Catppuccin
crust              = dce0e8
mantle             = e6e9ef
base               = eff1f5
surface0           = ccd0da
surface1           = bcc0cc 
surface2	       = 626880
overlay0           = 9ca0b0
overlay1           = 8c8fa1
overlay2           = 7c7f93
rosewater          = dc8a78
flamingo           = dd7878
pink               = ea76cb
maroon             = e64553
red                = d20f39
peach              = fe640b
yellow             = df8e1d
green              = 40a02b
teal               = 179299
sapphire           = 209fb5
blue               = 1e66f5
sky                = 04a5e5
mauve              = 8839ef
lavender           = 7287fd



[macchiato]
# Spicetify
text               = CAD3F5
subtext            = CAD3F5
main               = 24273A
main-elevated      = 363a4f
highlight          = 363b4f
highlight-elevated = 494d64
sidebar            = 1E2030
player             = 181926
card               = 363a4f
shadow             = 1E2030
selected-row       = 939ab7
button             = 8087A2
button-active      = 939AB7
button-disabled    = 6E738D
tab-active         = 363A4F
notification       = 363A4F
notification-error = ED8796
equalizer          = 000000
misc               = 494d64

# Catppuccin
crust              = 181926
mantle             = 1e2030
base               = 24273a
surface0           = 363a4f
surface1           = 494d64
surface2	       = 5b6078
overlay0           = 6e738d
overlay1           = 8087a2
overlay2           = 939ab7
rosewater          = f4dbd6
flamingo           = f0c6c6
pink               = f5bde6
maroon             = ee99a0
red                = ed8796
peach              = f5a97f
yellow             = eed49f
green              = a6da95
teal               = 8bd5ca
sapphire           = 7dc4e4
blue               = 8aadf4
sky                = 91d7e3
mauve              = c6a0f6
lavender           = b7bdf8


[mocha]
# Spicetify
text               = ebdbb2
subtext            = ebdbb2
main               = 282828
main-elevated      = 32302f
highlight          = 32302f
highlight-elevated = 3c3836
sidebar            = 1d2021
player             = 1d2021
card               = 32302f
shadow             = 1d2021
selected-row       = 504945
button             = fe8019
button-active      = d65d0e
button-disabled    = 665c54
tab-active         = 32302f
notification       = 32302f
notification-error = fb4934
equalizer          = 000000
misc               = 3c3836

# Gruvbox Dark
crust              = 1d2021
mantle             = 1d2021
base               = 282828
surface0           = 32302f
surface1           = 3c3836
surface2           = 504945
overlay0           = 665c54
overlay1           = 928374
overlay2           = a89984
rosewater          = d5c4a1
flamingo           = d3869b
pink               = d3869b
maroon             = fb4934
red                = fb4934
peach              = fe8019
yellow             = fabd2f
green              = b8bb26
teal               = 8ec07c
sapphire           = 458588
blue               = fe8019
sky                = 83a598
mauve              = d3869b
lavender           = b16286
