#!/usr/bin/env bash
# Rebuild ashell 0.10.0 with the MediaPlayer progress bar and install it to
# /usr/local/bin/ashell.
#
# Why a source build: stock ashell 0.10.0 has no way to show playback position.
# The MediaPlayer menu shows a volume slider but no progress bar, and MPRIS
# exposes no config knob for one. config/ashell/config.toml therefore cannot
# express this, so we carry a patch.
#
# Patches in config/ashell/patches/ are applied in filename order on top of the
# ASHELL_TAG checkout. Re-run this script after bumping ASHELL_TAG; a patch that
# no longer applies is a signal to rebase it by hand, not to skip it.
set -euo pipefail

ASHELL_TAG="${ASHELL_TAG:-0.10.0}"
REPO_URL="https://github.com/MalpenZibo/ashell.git"
BIN_PATH="/usr/local/bin/ashell"

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PATCH_DIR="$DOTFILES/config/ashell/patches"

SRC="${ASHELL_SRC_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/ashell-build}"
# Keep the build tree off tmpfs: a full ashell build is ~1.3G and /tmp is often
# a small tmpfs.
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$HOME/.cache/ashell-target}"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v cargo >/dev/null || die "cargo not found (install rustup)"

# --- build dependencies ------------------------------------------------------
# pipewire-sys (pulled in unconditionally by ashell's privacy service) runs
# bindgen, which needs libclang. Arch's `clang-libs` provides libclang.so; the
# package is not in packages.txt because it is a build-only dependency.
have_libclang() {
    # An explicit LIBCLANG_PATH wins, if it actually holds a library.
    if [ -n "${LIBCLANG_PATH:-}" ] && ls "$LIBCLANG_PATH"/libclang.so* >/dev/null 2>&1; then
        return 0
    fi
    ls /usr/lib/llvm-*/lib/libclang.so* >/dev/null 2>&1 && return 0
    ls /usr/lib/x86_64-linux-gnu/libclang*.so* >/dev/null 2>&1 && return 0
    command -v llvm-config >/dev/null 2>&1 && return 0
    return 1
}
if ! have_libclang; then
    die "libclang not found. Install it, e.g.: sudo pacman -S clang-libs
     (or point LIBCLANG_PATH at a directory containing libclang.so)"
fi

# --- fetch -------------------------------------------------------------------
if [ ! -d "$SRC/.git" ]; then
    log "cloning ashell $ASHELL_TAG into $SRC"
    mkdir -p "$(dirname "$SRC")"
    git clone --depth 1 --branch "$ASHELL_TAG" "$REPO_URL" "$SRC"
else
    log "reusing existing source at $SRC"
fi

git -C "$SRC" fetch --depth 1 origin "refs/tags/$ASHELL_TAG:refs/tags/$ASHELL_TAG" 2>/dev/null || true
git -C "$SRC" checkout --force "$ASHELL_TAG"

# --- patch -------------------------------------------------------------------
# `git apply --check` first so a bad patch fails here rather than halfway
# through a 15-minute build.
shopt -s nullglob
patches=("$PATCH_DIR"/*.patch)
shopt -u nullglob
[ ${#patches[@]} -gt 0 ] || die "no patches found in $PATCH_DIR"

git -C "$SRC" reset --hard >/dev/null
for p in "${patches[@]}"; do
    log "applying $(basename "$p")"
    git -C "$SRC" apply --check "$p" \
        || die "$(basename "$p") does not apply to $ASHELL_TAG; rebase it by hand"
    git -C "$SRC" apply "$p"
done

# --- build -------------------------------------------------------------------
log "building (this takes ~15 min; artifacts go to $CARGO_TARGET_DIR)"
mkdir -p "$CARGO_TARGET_DIR"
( cd "$SRC" && CARGO_TARGET_DIR="$CARGO_TARGET_DIR" cargo build --release )

BUILT="$CARGO_TARGET_DIR/release/ashell"
[ -x "$BUILT" ] || die "build produced no binary at $BUILT"
log "built $("$BUILT" --version)"

# --- install -----------------------------------------------------------------
if [ -w "$(dirname "$BIN_PATH")" ]; then
    install -m 755 "$BUILT" "$BIN_PATH"
    log "installed to $BIN_PATH"
else
    log "$BIN_PATH is not user-writable, falling back to sudo"
    sudo install -m 755 "$BUILT" "$BIN_PATH"
    log "installed to $BIN_PATH"
fi

cat <<EOF

Done. Restart ashell to pick up the new build:

    kill \$(pgrep -x ashell); ashell &

Note: ~/.config/ashell/config.toml is unchanged by this script. The patch only
adds the progress bar to the MediaPlayer menu; everything else in that file
(theming, modules, cat glyphs) is still generated by local/bin/theme-apply.
EOF
