-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "21")

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.9,
        -- The frosted-glass effect. This is Hyprland's own blur, applied to the
        -- desktop behind a window, and it is what makes kitty look like glass --
        -- it only shows through because kitty's own background_opacity is below
        -- one.
        --
        -- It is NOT kitty's background_blur, which would be the tidier route.
        -- That option needs the compositor to advertise ext-wlr-blur-v1, and
        -- Hyprland does not: it offers ext_background_effect_v1 instead. Setting
        -- it here would be a line that silently does nothing.
        --
        -- size is the frost radius and is what sells the effect; 4 is barely
        -- visible, which is why it looked flat before. passes smooths the
        -- banding that shows on large radii.
        --
        -- Cost: this is a software blur on an Intel HD 520 with 4 cores, and
        -- blur was previously removed from the niri config for that reason. If
        -- scrolling or the compositor feels heavy, drop size to 8 or passes to 1
        -- before turning it off -- size is the expensive one.
        blur = {
            size = 16,
            passes = 3,
        },
        inactive_opacity = 0.9,
        rounding = 14,
    },
    general = {
        border_size = 0,
        col = {
            active_border = {
                colors = {"rgba(c0bfbcff)"},
                angle = 54,
            },
        },
        gaps_out = 7,
        layout = "dwindle",
    },
})
