-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "20")

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.9,
        blur = {
            contrast = 0.9,
            enabled = true,
            size = 3,
            xray = true,
        },
        dim_around = 0.0,
        dim_inactive = false,
        dim_special = 0.2,
        fullscreen_opacity = 1.0,
        inactive_opacity = 0.9,
        rounding = 11,
        shadow = {
            enabled = true,
        },
    },
    general = {
        border_size = 0,
        col = {
            active_border = "0xfff0f0f0",
        },
        gaps_in = 5,
        gaps_out = 5,
    },
})
